/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "c110p_serial.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(C110PCommand, C110PCommand, AUTO)


PB_BIND(AckCommand, AckCommand, AUTO)


PB_BIND(LedCommand, LedCommand, AUTO)


PB_BIND(MoveCommand, MoveCommand, AUTO)


PB_BIND(SoundCommand, SoundCommand, AUTO)







